#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.


# POR MI
echo
   (echo "BORRANDO FOLDERS APP_ROOT/DATA............" >> "$OPENSHIFT_LOG_DIR/npm.log"; cd "${OPENSHIFT_DATA_DIR}"; rm -r .config .local .nodejs.tmp .nodewatch; echo "FOLDERS APP_ROOT/DATA BORRADOS" >> "$OPENSHIFT_LOG_DIR/npm.log")


